apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-express-kubernetes-example-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: node-express-kubernetes-example-letsencrypt-dev
spec:
  tls:
  - hosts:
    - node-example.juffalow.com
    secretName: node-express-kubernetes-example-tls
  rules:
  - host: node-example.juffalow.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-express-kubernetes-example-cluster-ip
            port: 
              number: 80
