apiVersion: v1
kind: Secret
metadata:
  name: node-express-kubernetes-example-secret
data:
  # Value: DatabaseCredentials
  # To generate base64 secret, you need to take the value
  # and use command: echo -n "<value>" | base64
  SECRET_PARAMETER: RGF0YWJhc2VDcmVkZW50aWFscw==
