apiVersion: v1
kind: Service
metadata:
  name: node-express-kubernetes-example-cluster-ip
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3001
  selector:
    app: node-express-kubernetes-example-deployment
  type: ClusterIP